// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWPbOMuLPkfO7Mw0ADSm4UjdWuoYkOIs0',
    appId: '1:89469169979:web:d5b1ca7dd791738d77071e',
    messagingSenderId: '89469169979',
    projectId: 'gailtrack-32b7b',
    authDomain: 'gailtrack-32b7b.firebaseapp.com',
    storageBucket: 'gailtrack-32b7b.firebasestorage.app',
    measurementId: 'G-5K1KZ5F37L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW0rBbUWJgp5RVosWWAgtgCWtnq-9Fers',
    appId: '1:89469169979:android:7384c9a254d724bb77071e',
    messagingSenderId: '89469169979',
    projectId: 'gailtrack-32b7b',
    storageBucket: 'gailtrack-32b7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCd3sYYFilHLJP57enB0a3mQ5CUHFbW14',
    appId: '1:89469169979:ios:cf855d1263892eb177071e',
    messagingSenderId: '89469169979',
    projectId: 'gailtrack-32b7b',
    storageBucket: 'gailtrack-32b7b.firebasestorage.app',
    iosBundleId: 'com.example.gailtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCd3sYYFilHLJP57enB0a3mQ5CUHFbW14',
    appId: '1:89469169979:ios:cf855d1263892eb177071e',
    messagingSenderId: '89469169979',
    projectId: 'gailtrack-32b7b',
    storageBucket: 'gailtrack-32b7b.firebasestorage.app',
    iosBundleId: 'com.example.gailtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWPbOMuLPkfO7Mw0ADSm4UjdWuoYkOIs0',
    appId: '1:89469169979:web:bcb1c285e083632a77071e',
    messagingSenderId: '89469169979',
    projectId: 'gailtrack-32b7b',
    authDomain: 'gailtrack-32b7b.firebaseapp.com',
    storageBucket: 'gailtrack-32b7b.firebasestorage.app',
    measurementId: 'G-7JJCKD1HBD',
  );
}
